import React,{useState,useEffect}from'react';
import{ArrowUpRight,Mail,LockKeyhole,Check,ArrowLeft}from'lucide-react';
import{supabase,authAction,authSetupError}from'../supabase';
export function AuthForm({signup,toggle,onSignedIn,CityInput}){
 const[city,setCity]=useState('Detroit'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(''),[reset,setReset]=useState(false),[email,setEmail]=useState('');
 useEffect(()=>{setError('');setSent('');setReset(false)},[signup]);
 async function submit(e){e.preventDefault();setError('');setBusy(true);const values={...Object.fromEntries(new FormData(e.currentTarget)),city};try{
  if(reset){await authAction('reset-request',values);setSent('If that address has an account, a password reset link is on its way.');}
  else{const data=await authAction(signup?'signup':'login',values);if(signup&&!data.session)setSent('Check your email to confirm your account. Follow the link, then return here to sign in.');else await onSignedIn();}
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><div className="auth-intro"><span className="auth-symbol">{sent?<Mail/>:<LockKeyhole/>}</span><p>{reset?'A fresh start for your password.':signup?'A shared future starts with a neighbor.':'Your resources, your people, your place.'}</p></div>{!supabase&&<p className="notice">{authSetupError}</p>}{error&&<p className="form-error" role="alert">{error}</p>}{sent?<div className="confirmation-state" role="status"><Mail/><h3>{reset?'Check your inbox.':'You’re almost home.'}</h3><p>{sent}</p>{!reset&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await authAction('resend',{email});setSent('A new confirmation email has been requested. Check your inbox and spam folder.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Resend confirmation</button>}<button className="text-button" onClick={()=>{setSent('');if(signup)toggle();setReset(false)}}>Back to sign in <ArrowUpRight size={16}/></button></div>:<form onSubmit={submit}>{signup&&!reset&&<><label>Your name<input name="name" autoComplete="name" required placeholder="First and last name" maxLength={200}/></label><CityInput value={city} onChange={setCity}/></>}<label>Email address<input type="email" name="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>{!reset&&<label>Password<input type="password" name="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?10:undefined} required placeholder={signup?'At least 10 characters':'Your password'}/></label>}{signup&&!reset&&<small>We’ll send an email to confirm your account.</small>}<button className="primary" disabled={busy||!supabase}>{busy?'One moment…':reset?'Send reset link':signup?'Create account':'Log in'}<ArrowUpRight size={17}/></button>{!signup&&!reset&&<button className="text-button" type="button" onClick={()=>setReset(true)}>Forgot your password?</button>}<button className="text-button" type="button" onClick={()=>{if(reset)setReset(false);else toggle()}}>{reset?'Back to sign in':signup?'Already a neighbor? Log in':'New here? Create an account'}</button></form>}</>}
export function RecoveryPage({onComplete}){const[session,setSession]=useState(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const{data}=supabase.auth.onAuthStateChange((event,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);return <section className="panel recovery-panel"><span className="auth-symbol"><LockKeyhole/></span><span className="eyebrow">YOUR ACCOUNT</span><h1>A fresh start.</h1>{error&&<p className="form-error" role="alert">{error}</p>}{success?<><p role="status">Your password has been updated.</p><button className="primary" onClick={onComplete}>Go to dashboard <ArrowUpRight size={16}/></button></>:!ready?<p>Checking your recovery link…</p>:!session?<p>This reset link is missing or expired. Return home and request a new password reset from Log in.</p>:<form onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(d.password!==d.confirm)return setError('The passwords do not match.');setBusy(true);try{await authAction('recovery',d);setSuccess(true)}catch(e){setError(e.message)}finally{setBusy(false)}}}><p>Choose a new password for your account.</p><label>New password<input name="password" type="password" autoComplete="new-password" minLength={10} required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={10} required/></label><button disabled={busy} className="primary">{busy?'Saving…':'Update password'}</button></form>}</section>}
