import {supabase, authAction} from './supabase';
export const groups={
'Food & Agriculture':['Pantry Staples & Grains','Fresh Produce & Orchard Crop','Livestock & Poultry','Dairy & Eggs','Meats & Seafood','Baking & Sweeteners','Spices & Condiments','Beverages (Coffee, Tea, Juices)','Preserved & Canned Foods','Gardening Supplies & Seeds','Animal Feed & Forage','Beekeeping & Honey Production'],
'Water, Sanitation & Hygiene':['Water Purification & Filtration','Water Storage & Transport','Personal Hygiene & Toiletries','Sanitation & Waste Management','Feminine Care Products','Baby Care & Diapering','Cleaning Chemicals & Detergents','Off-Grid Sanitation Facilities'],
'Health, Medical & Wellness':['First Aid & Trauma Supplies','Over-the-Counter Medications','Medical Equipment & Diagnostics','Herbals & Home Remedies','Dental Care Products','Vision Care & Eyewear','Physical Therapy & Bodywork','Medical & Nursing Services','Veterinary & Pet Care'],
'Tools, Hardware & Building':['Hand Tools','Power Tools & Accessories','Hardware & Fasteners','Lumber & Building Materials','Plumbing Materials & Fixtures','Electrical Supplies & Wiring','Fencing & Enclosures','Paints, Sealants & Adhesives','Rope, Chain & Rigging','Carpentry & Woodworking','Welding & Metal Fabrication','Masonry & Concrete','Sharpening & Tool Maintenance'],
'Energy, Heating & Fuel':['Liquid & Gas Fuels','Solid Fuels (Firewood, Charcoal)','Fire-Starting Gear & Tinder','Primary & Rechargeable Batteries','Solar Power Systems & Panels','Generators & Inverters','Emergency & Off-Grid Lighting','Heating & Stoves','Portable Power Stations','Fuel Storage Containers'],
'Clothing, Textiles & Outdoor Gear':['Workwear & Outerwear','Footwear & Boots','Thermal & Cold-Weather Gear','Rain Protection & Waterproofing','Fabrics, Canvas & Leather','Sewing & Garment Repair Supplies','Bedding & Sleeping Bags','Camping & Shelter Gear','Backpacks & Load-Bearing Gear','Tactical & Protective Apparel'],
'Transportation, Motors & Machinery':['Automotive Parts & Accessories','Small Engine Repair & Parts','Bicycles & Human-Powered Transport','Tires, Chains & Repair Kits','Fluids, Oils & Lubricants','Heavy Equipment & Trailers','Boats, Watercraft & Marine Gear','Vehicle Maintenance Labor','Towing & Recovery Gear'],
'Vices, Commodities & Store of Value':['Precious Metals (Silver & Gold)','Bullion & Collectible Coins','Tobacco & Accessories','Alcoholic Beverages','Coffee Beans & Luxury Sweets','Ammunition & Reloading Supplies','Knives & Blades','Jewelry & Wearable Wealth','Self-Defense Gear'],
'Professional Services & Trade Labor':['General Contracting & Construction','Roofing & Exterior Repair','Landscaping & Land Clearing','Tailoring & Clothing Alteration','Barbering & Hair Styling','Childcare & Babysitting','Accounting, Tax & Bookkeeping','Legal Services & Mediation','Graphic Design & Digital Services','IT, Computer & Appliance Repair','Photography & Media Production'],
'Education, Knowledge & Entertainment':['Academic Tutoring & Test Prep','Music Lessons & Instrument Care','Survival & Bushcraft Instruction','Fitness & Personal Training','Language Learning & Translation','Physical Books & Manuals','Board Games, Cards & Puzzles','Crafting & Hobby Supplies','Dog & Animal Training']};
export const resources=[['gardens','Gardens & food','Sprout','Grow together. Share the harvest.','Track harvests, exchange fresh produce, and give every crop a traceable origin.'],['kinetic','Kinetic power','Zap','Your energy goes further.','Pedal and row to help power the neighborhood. Verified generation earns one credit per kWh.'],['carpentry','Carpentry & tools','Hammer','Build something that lasts.','Share tools, exchange woodworking skills, and build raised beds or repair community infrastructure.'],['water-supply','Water supply','Droplets','Fresh water. From thin air.','Community energy powers atmospheric water generation and shared drinking water infrastructure.'],['greenhouse','Greenhouse','Leaf','A little room for growth.','Share seedlings and steward a climate-controlled nursery for year-round food production.'],['solar','Solar micro-grid','Sun','A shared place in the sun.','Contribute surplus solar energy to the water station, workshop, and community battery.'],['bitchat','Emergency mesh','Radio','Stay connected. Even offline.','Keep resource requests queued during outages and use native Bitchat for nearby Bluetooth messaging.']];
export const api=async(path,body)=>{
 if(['signup','login','logout','password','reset-request','resend','recovery'].includes(path))return authAction(path,body);
 const session=supabase?(await supabase.auth.getSession()).data.session:null;
 const headers={...(session?{Authorization:'Bearer '+session.access_token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})};
 const r=await fetch('/api/'+path,{headers,...(body!==undefined?{method:'POST',body:JSON.stringify(body)}:{})});
 const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;
};
